### ISSUE TITLE
Message not displaying/hiding under keyboard after sending 

### ISSUE THREAD

**Issue by shamxeed** [flyerhq/react-native-chat-ui#26]
By default when sending a message a user expects the chat thread to scroll up a bit in order to show the newly sent message. But that's not a default behaviour here I guess. Is there any way, workaround to solve this? Below is a short video to demonstrate the issue.

THANKS!

https://user-images.githubusercontent.com/57716026/120024352-f2186380-bfe6-11eb-93fe-e0973188c4ba.mp4

**Comment by demchenkoalex** [comment]
@vdanylov can you check that? thanks

**Comment by vdanylov** [comment]
@shamxeed Hello, could You please share You implementation that we can recommend how to handle it. I've checked Your problem on emulator, here is the result:

https://user-images.githubusercontent.com/20551843/120100489-564f3a80-c141-11eb-8566-82ad7edf0ad7.mov

**Comment by shamxeed** [comment]
Thanks, @vdanylov for the response, after your response I tried to change how I update my state and it works just fine... Couldn't be happier!!

**Comment by jamninetyfive** [comment]
same here. how do you reslove it .@[shamxeed](https://github.com/shamxeed)

**Comment by shamxeed** [comment]
@jamninetyfive I forced a re-render by creating new array of messages every time a new message is added. 
eg 
```jsx
chat.messages = [newMessage, …chat.messages]
```

hope this helps , if not please let me know.
