### ISSUE TITLE
I am getting this below error

### ISSUE THREAD

**Issue by srivastavaanurag79** [flyerhq/react-native-chat-ui#36]
everytime i try to tun the example it says: 

 Error: While trying to resolve module `@flyerhq/react-native-chat-ui` from file `C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\src\App.tsx`, the package `C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\lib\index.js`. Indeed, none of these files exist:

  * C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\lib\index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\lib\index.js\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\node-haste\DependencyGraph.js:311:17)
    at Object.resolve (C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at async addDependency (C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
    at async Promise.all (index 2)
    at async processModule (C:\Users\sriva\Downloads\react-native-chat-ui-main (1)\react-native-chat-ui-main\example\node_modules\metro\src\DeltaBundler\traverseDependencies.js:198:5)

**Comment by demchenkoalex** [comment]
Hey @srivastavaanurag79 why is there (1) in the path? Do you have 2 folders there? Can you remove everything and start from scratch?

**Comment by srivastavaanurag79** [comment]
cleaned everything cloned in a fresh folder same error

**Comment by demchenkoalex** [comment]
Sam error with (1) in the path?

**Comment by demchenkoalex** [comment]
Ah, did you do yarn command in the both root and example? Cause it can't find lib folder that means you didn't compile the lib

**Comment by srivastavaanurag79** [comment]
Yes tried everything, more than two times. Had this issue last month also thought would be resolved in the next update or commit. But the issue is still there.

**Comment by srivastavaanurag79** [comment]
> Sam error with (1) in the path?

Yes

**Comment by srivastavaanurag79** [comment]
> Ah, did you do yarn command in the both root and example? Cause it can't find lib folder that means you didn't compile the lib

It just won't work, tried in a windows laptop and a MacBook pro, for iOS and Android both.

**Comment by demchenkoalex** [comment]
How is that not working? You need to install dependencies to run the project. You mean yarn command not working?

**Comment by srivastavaanurag79** [comment]
I mean after running the yarn command it shows that error strace

**Comment by demchenkoalex** [comment]
But yarn just installs dependencies, and this is typical error when the project is running. Are you sure that you can't just simply install dependencies?

**Comment by demchenkoalex** [comment]
Just did clone and install on a new Mac (not used to develop the library), everything runs (I have latest node, yarn, android studio). Once again:

1. `yarn` to install dependencies in the root folder
2. `yarn` to install dependencies in the example folder
3. `yarn android` to run the app from the example folder

If for some reason example does not compile on Windows, better to help me understand what are the commands you're doing, rather than throwing random accusations. I don't have access to Windows, so I am sorry I can't test there.

Alternatively, rather than using example from the project, you can just add the library through npm and just use it in your project directly, which I believe is configured to work on Windows.

Have a nice day.

**Comment by srivastavaanurag79** [comment]
> Just did clone and install on a new Mac (not used to develop the library), everything runs (I have latest node, yarn, android studio). Once again:
> 
> 1. `yarn` to install dependencies in the root folder
> 2. `yarn` to install dependencies in the example folder
> 3. `yarn android` to run the app from the example folder
> 
> If for some reason example does not compile on Windows, better to help me understand what are the commands you're doing, rather than throwing random accusations. I don't have access to Windows, so I am sorry I can't test there.
> 
> Alternatively, rather than using example from the project, you can just add the library through npm and just use it in your project directly, which I believe is configured to work on Windows.
> 
> Have a nice day.

I have followed all the above steps with yarn and npm, it shows the same error.

**Comment by srivastavaanurag79** [comment]
> > Just did clone and install on a new Mac (not used to develop the library), everything runs (I have latest node, yarn, android studio). Once again:
> > 
> > 1. `yarn` to install dependencies in the root folder
> > 2. `yarn` to install dependencies in the example folder
> > 3. `yarn android` to run the app from the example folder
> > 
> > If for some reason example does not compile on Windows, better to help me understand what are the commands you're doing, rather than throwing random accusations. I don't have access to Windows, so I am sorry I can't test there.
> > Alternatively, rather than using example from the project, you can just add the library through npm and just use it in your project directly, which I believe is configured to work on Windows.
> > Have a nice day.
> 
> I have followed all the above steps with yarn and npm, it shows the same error. Installing directly in the project throws the same error.

Have a nice day.

**Comment by gwbischof** [comment]
I was getting this same error, following the steps suggested revealed that I needed to update my node version.  Updating node, and following the procedure again fixed the problem.

**Comment by dranitski** [comment]
Steps for total noobs:

1. `yarn` to install dependencies in the root folder
2. `yarn` to install dependencies in the example folder
3. `yarn start` in the example folder to run metro
4. `yarn android` to run the app from the example folder
