### ISSUE TITLE
There is a bottom space of input on iOS

### ISSUE THREAD

**Issue by phucgo240699** [flyerhq/react-native-chat-ui#37]
.

**Comment by demchenkoalex** [comment]
Can you post a screenshot? Thanks

**Comment by RayVR** [comment]
I have the same issue. I believe the space is related to using BottomTabs, at least in my case.

I can post a screenshot when I'm back at my machine.

**Comment by demchenkoalex** [comment]
If both cases are on top of the bottom tab navigation, this will not work anyway, since I am using my https://github.com/flyerhq/react-native-keyboard-accessory-view. I can check if this can be disabled, but honestly, never saw a chat on top of bottom tab navigation.

**Comment by kratebox** [comment]
![Simulator Screen Shot - iPhone 12 - 2021-12-19 at 18 40 27](https://user-images.githubusercontent.com/50448516/146676018-e52a182d-7512-48b4-bb04-7271a4536d89.png)

Looks like this. Not able to figure out how to remove the empty space in input chat.

**Comment by kratebox** [comment]
had to put the Chat inside a SafeAreaProvider as given in the example. this fixed it for me

**Comment by demchenkoalex** [comment]
I guess `SafeArea` should work and chat on top of bottom tab navigation is not supported, don't see any other cases where this might happen, but feel free to reopen with more information if needed.
