### ISSUE TITLE
[QUESTION]: How to render custom message ?

### ISSUE THREAD

**Issue by shamxeed** [flyerhq/react-native-chat-ui#39]
> I am not completely sure whether my codes follows good PRACTICE, that's why I'm here.

In a room chat, I want the current room members to be notified of newly joined member through rendering customMessage.

my code: 

```jsx
import { Dimensions } from 'react-native'
import { Chat, defaultTheme } from '@flyerhq/react-native-chat-ui';

//first off, let's get the screen width
const { width } = Dimensions.get('screen');

const ChatWindow = () => {
 return (
    <Chat
      ...
      renderCustomMessage={(message) => {
        if (message?.type !== 'custom') return;
        return (
          <View
            style={{
              width: width - 20,
              backgroundColor: background,
              paddingVertical: 10,
              alignItems: 'center',
            }}
          >
            <Paragraph>{message?.text}</Paragraph>
          </View>
        );
      }}
    />
 )
}

```

Please, if there's a better approach to archive this,  let me know. And I think more examples are needed In the documentations, Thank you so much for this amazing Lib, words can't describe how amazing it was!!

PS: Screenshot provided below.

![2021_12_22_12_06_IMG_2880](https://user-images.githubusercontent.com/57716026/147085664-35c654a8-4fde-4005-80e4-44e5392cf9fe.PNG)

**Comment by demchenkoalex** [comment]
Hey @shamxeed sorry for the late response, had health issues. For now what you have is exactly how it can be done at the moment, but we will be soon working on a dedicated `SystemMessage` which will be used exactly for this purpose - notification.

**Comment by shamxeed** [comment]
Firstly, very disheartening to hear about your health condition and pray
you for a speedy recovery. Okay, I will use that as a work-around until the
feature is been implemented or included. Thanks!! :))

**Comment by shamxeed** [comment]
By the way, is it possible to add caption to image message?

**Comment by demchenkoalex** [comment]
not at the moment, no. To add a caption to the image we would need to create a custom image picker (to store selected image somewhere while adding caption) and this might be the whole different big project to be honest :) so right now you can only send an image and then write a message.

**Comment by shamxeed** [comment]
Okay thanks! And very well understood!😊😊
