### ISSUE TITLE
Any plan on Vue?

### ISSUE THREAD

**Issue by Marcnuth** [flyerhq/react-native-chat-ui#40]
Flyer chat ui is really good,  but I can not find a Vue implementation for this? 

is there any plans for supporting Vue?

**Comment by demchenkoalex** [comment]
Hey @Marcnuth sorry for the late response. As you can see this package still require a lot of things to do and there is also 1:1 Flutter implementation (https://github.com/flyerhq/flutter_chat_ui) and I am maintaining all of that pretty much alone (there are also 7 different repos in this project. I will definitely die if we will add Vue or anything else :)

**Comment by Marcnuth** [comment]
haha, thanks @demchenkoalex  anyway for this beautiful chat ui.
it's really great when i found it in flutter!
