### ISSUE TITLE
Chat UI and message box issue on iOS with react native expo

### ISSUE THREAD

**Issue by anistark** [flyerhq/react-native-chat-ui#87]
Integrating in React Native Expo app.

## What bug do you experience? 🐞
1 issues in ios:
1. The keypad appears but the message box is still below, so can't see anything that's been typed in.
2. When closing the keypad, the chat window goes below the message box, so as to hide the text underneath it.

Works fine with Android.

## How can it be reproduced? 🤔
Integrate into a react native ios app and build it.

## What behavior is expected? 💡
Same behavior as in android.

<br />

# Extras

## Screenshots or videos 📸
![IMG_0575](https://github.com/flyerhq/react-native-chat-ui/assets/5357586/c180d10e-095a-4bdb-829f-258038351046)
![IMG_0576](https://github.com/flyerhq/react-native-chat-ui/assets/5357586/892781bb-90e3-4dae-9b9a-01925d45e57f)

## Code snippets 📝
Just using normal example from docs.
```ts
<SafeAreaProvider style={styles.chatContainer}>
          <MemoizedChat
            messages={memoizedMessages}
            onPreviewDataFetched={handlePreviewDataFetched}
            onSendPress={handleSendPress}
            onEndReached={handleEndReached}
            user={{
              ...user,
              id: user?._id as string,
            }}
            theme={{
              ...defaultTheme,
              colors: {
                ...defaultTheme.colors,
                background: '#02020349',
                inputBackground: "#5260D1FF",
              },
            }}
            showUserNames={true} />
</SafeAreaProvider>
```

<br />

# Environment info

Please specify the react, react-native, react-native-chat-ui versions.

react: `18.2.0`
react-native: `0.71.6`
react-native-chat-ui: `1.4.3`
expo: `48.0.7`

`npx react-native info` output 👇

```sh
info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Apple M1
    Memory: 20.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.6 => 0.71.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): iPhone 11

OS version (e.g. iOS 14.5, Android 11): iOS 16.3.1

<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by anistark** [comment]
@demchenkoalex Would be able to shed some light to this issue?
If you're occupied, please point in the right direction so I can explore about fixing it.

**Comment by demchenkoalex** [comment]
Hi @anistark this repo is abandoned for now, I wouldn't suggest using it (only fork). I don't have capacity to maintain it, but want to revive it in the future if time allows. I will be re-writing everything from scratch anyway, so current implementation will not be useful.

**Comment by anistark** [comment]
Thanks for responding @demchenkoalex 

Any starting point on how to fix it till your new version comes up.

Can help maintain the new version if it helps.

**Comment by demchenkoalex** [comment]
never used expo tbh, so not sure. I remember that everything was working correctly on a usual react native project, like here in the example :/

**Comment by anistark** [comment]
It works perfectly fine on android. But on ios it's acting weird.

I was able to hack fix the issue on keyboard open by pushing it a bit further up using `KeyboardAvoidingView` as such:

```
<KeyboardAvoidingView
    behavior="padding"
    keyboardVerticalOffset={-167}
>
```

But on keyboard exit, the messages scrolls below the box. If I exit the screen and come back, it's back to normal.

**Comment by atipezda** [comment]
@anistark any news?

**Comment by anistark** [comment]
> @anistark any news?

Haven't worked on this in a while. Although I remember fixing it somehow.
But as Alex mentioned above, this project is not maintained anymore.

Are you also working on this?

**Comment by BijuDey** [comment]
> It works perfectly fine on android. But on ios it's acting weird.
> 
> I was able to hack fix the issue on keyboard open by pushing it a bit further up using `KeyboardAvoidingView` as such:
> 
> ```
> <KeyboardAvoidingView
>     behavior="padding"
>     keyboardVerticalOffset={-167}
> >
> ```
> 
> But on keyboard exit, the messages scrolls below the box. If I exit the screen and come back, it's back to normal.

` flatListProps={{
            contentContainerStyle: {paddingTop: Platform.OS == 'ios' ? 100 : 0},
          }}`
          Temporary fix for "But on keyboard exit, the messages scrolls below the box. If I exit the screen and come back, it's back to normal."

**Comment by demchenkoalex** [comment]
please use alternative libraries as of right now. If I come back to this, this will be a completely different library, keeping repo just in case I will have a possibility to come back.
